services:
  it-tools:
    image: 'corentinth/it-tools:latest'
    restart: unless-stopped
    container_name: it-tools
    networks:
      services:
        ipv4_address: your.desired.ip.address

networks:
  services:
    name: services
    external: true