services:
  cloudflared:
    image: cloudflare/cloudflared
    restart: unless-stopped
    container_name: pihole_cloudflared
    command: proxy-dns
    environment:
      TUNNEL_DNS_UPSTREAM: 'https://9.9.9.9/dns-query,https://149.112.112.9/dns-query,https://1.1.1.1/dns-query,https://1.0.0.1/dns-query'
      TUNNEL_DNS_PORT: '5053'
      TUNNEL_DNS_ADDRESS: '0.0.0.0'
    networks:
      internal:
        ipv4_address: your.desired.address.here
  pihole:
    image: pihole/pihole
    restart: unless-stopped
    container_name: pihole_webui
    env_file:
      - .env
    volumes:
      - pihole_config:/etc/pihole/
      - pihole_dnsmasq:/etc/dnsmasq.d/
    networks:
      internal:
        ipv4_address: your.desired.address.here
      home:
        ipv4_address: your.desired.address.here
      services:
        ipv4_address: your.desired.address.here
    depends_on:
      - cloudflared

volumes:
  pihole_config:
    name: pihole_config
    external: true
  pihole_dnsmasq:
    name: pihole_dnsmasq
    external: true

networks:
  internal:
    ipam:
      config:
        - subnet: your.desired.address.here/29
  home:
    name: home
    external: true
  services:
    name: services
    external: true