services:
  zerotier:
    image: zerotier-debian:latest
    restart: unless-stopped
    container_name: zerotier
    devices:
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN