services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=443
      - DOCKER_MTU=1500
    volumes:
      - kasm_data:/opt
      - kasm_profiles:/profiles #optional
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    networks:
      services:
        ipv4_address: your.desired.address.here
    restart: unless-stopped

volumes:
  kasm_data:
    external: true
  kasm_profiles:
    external: true

networks:
  services:
    name: services
    external: true