services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    container_name: portainer
    networks:
      services:
        ipv4_address: your.desired.address.here
      home:
        ipv4_address: your.desired.address.here
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer_data:
    name: portainer_data
    external: true

networks:
  services:
    name: services
    external: true
  home:
    name: home
    external: true
