services:
  nginx-proxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: nginx-proxymanager
    ports:
      - 80:80
      - 443:443
      - 81:81
    networks:
      services:
        ipv4_address: your.desired.address.here
    volumes:
      - nginx-proxymanager_data:/data
      - nginx-proxymanager_letsencrypt:/etc/letsencrypt

volumes:
  nginx-proxymanager_data:
    name: nginx-proxymanager_data
    external: true
  nginx-proxymanager_letsencrypt:
    name: nginx-proxymanager_letsencrypt
    external: true

networks:
  services:
    name: services
    external: true