services:
  nginx-proxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: nginx-proxymanager
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    networks:
      services:
        ipv4_address: your.desired.address.here
    volumes:
      - nginx_proxymanager-data:/data
      - nginx_proxymanager-letsencrypt:/etc/letsencrypt

volumes:
  nginx_proxymanager-data:
    name: nginx_proxymanager-data
    external: true
  nginx_proxymanager-letsencrypt:
    name: nginx_proxymanager-letsencrypt
    external: true

networks:
  services:
    name: services
    external: true